
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package GUI;

import Model.pelatihan;
import Service.pelatihanService;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import util.koneksi;


/**
 *^
 * @author user
 */
public final class adminPelatihan extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminPelatihan.class.getName());
        public void loadDataPelatihan() throws Exception {
            DefaultTableModel model = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            model.addColumn("ID Pelatihan");
            model.addColumn("Nama Pelatihan");
            model.addColumn("Deskripsi");
            model.addColumn("Tanggal Mulai");
            model.addColumn("Tanggal Selesai");
            model.addColumn("Status Program");


            pelatihanService service = new pelatihanService();
            List<pelatihan> daftar = service.getAllPelatihan();

            for (pelatihan p : daftar) {
                model.addRow(new Object[]{
                    p.getId(),
                    p.getNama(),
                    p.getDeskripsi(),
                    p.getTanggalMulai(),
                    p.getTanggalSelesai(),
                    p.getStatusProgram()
                });
            }

            jTable2.setModel(model);
        }
        
    /**
     * Creates new form utamaAdmin
     */
    public adminPelatihan() throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        
        jDateChooser2.getDateEditor().addPropertyChangeListener(evt -> {
            if ("date".equals(evt.getPropertyName())) {
                java.util.Date tglMulai = jDateChooser1.getDate();
                java.util.Date tglSelesai = jDateChooser2.getDate();

                if (tglMulai != null && tglSelesai != null) {
                    if (tglSelesai.before(tglMulai)) {
                        JOptionPane.showMessageDialog(this,
                            "Tanggal Selesai tidak boleh sebelum Tanggal Mulai!",
                            "Tanggal Tidak Valid",
                            JOptionPane.WARNING_MESSAGE
                        );
                        jDateChooser2.setDate(null); // reset tanggal selesai
                    }
                }
            }
        });
        
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getClickCount() == 2) { 
                int row = jTable2.getSelectedRow(); 
                if (row != -1) {

                    jTextField2.setText(jTable2.getValueAt(row, 0).toString());
                    jTextField4.setText(jTable2.getValueAt(row, 1).toString());
                    jTextField6.setText(jTable2.getValueAt(row, 2).toString());

                    String status = jTable2.getValueAt(row, 5).toString().trim().toLowerCase();

                    if (status.contains("belum")) {
                        jComboBox1.setSelectedItem("Belum Mulai");
                    } else if (status.contains("jalan")) {
                        jComboBox1.setSelectedItem("Berjalan");
                    } else if (status.contains("selesai")) {
                        jComboBox1.setSelectedItem("Selesai");
                    }

                    try {
                        jDateChooser1.setDate((java.util.Date) jTable2.getValueAt(row, 3));
                        jDateChooser2.setDate((java.util.Date) jTable2.getValueAt(row, 4));
                    } catch (Exception ex) {}
                }
            }
        } 
    });
        
        loadDataPelatihan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(410, 30));

        jTextField6.setBackground(new java.awt.Color(217, 217, 217));
        jTextField6.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(37, 37, 37));
        jTextField6.setBorder(null);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(217, 217, 217));
        jComboBox1.setForeground(new java.awt.Color(37, 37, 37));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Mulai", "Berjalan", "Selesai" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 410, 25));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(410, 30));

        jTextField4.setBackground(new java.awt.Color(217, 217, 217));
        jTextField4.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(37, 37, 37));
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 410, 25));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(410, 30));

        jTextField2.setBackground(new java.awt.Color(217, 217, 217));
        jTextField2.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(37, 37, 37));
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(217, 217, 217));
        jDateChooser1.setForeground(new java.awt.Color(37, 37, 37));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 410, 25));

        jPanel2.setBackground(new java.awt.Color(0, 52, 188));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Inter 24pt", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(37, 37, 37));
        jButton3.setText("Daftar Staff");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Inter 24pt", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(37, 37, 37));
        jButton7.setText("Daftar Pelatihan");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Inter 24pt", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(37, 37, 37));
        jButton8.setText("Daftar Peserta");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Inter 24pt", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(37, 37, 37));
        jButton9.setText("Daftar Pendaftar");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Inter 24pt", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 52, 188));
        jButton5.setText("Keluar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 40, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 40, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 332, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 370));

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(37, 37, 37));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 520, 190));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 52, 188));
        jButton1.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Hapus");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 52, 188));
        jButton2.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Perbarui");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 52, 188));
        jButton4.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Tambah");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 110, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ImageIcon/adminpelatihan.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     String idPelatihan = jTextField2.getText().trim();

    if(idPelatihan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih pelatihan yang akan dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(this, 
        "Apakah Anda yakin ingin menghapus pelatihan ini?", 
        "Konfirmasi Hapus", 
        JOptionPane.YES_NO_OPTION);

    if(konfirmasi == JOptionPane.YES_OPTION) {
        try {
            Connection conn = koneksi.getConnection();
            String sql = "DELETE FROM pelatihan WHERE id_pelatihan=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, idPelatihan);

            int deleted = pst.executeUpdate();
            if(deleted > 0) {
                JOptionPane.showMessageDialog(this, "Pelatihan berhasil dihapus!");
                loadDataPelatihan(); 
                
                jTextField2.setText("");
                jDateChooser1.setDate(null);
                jDateChooser2.setDate(null);
                jTextField4.setText("");
                jComboBox1.setSelectedIndex(0);
                jTextField6.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "ID Pelatihan tidak ditemukan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }

            pst.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus pelatihan: " + e.getMessage());
        } catch (Exception e) {
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String idPelatihan = jTextField2.getText().trim();
        String namaPelatihan = jTextField4.getText().trim();
        String deskripsi = jTextField6.getText().trim();
        String status = jComboBox1.getSelectedItem().toString();

        java.util.Date tglMulaiUtil = jDateChooser1.getDate();
        java.util.Date tglSelesaiUtil = jDateChooser2.getDate();

        if(idPelatihan.isEmpty() || tglMulaiUtil == null || tglSelesaiUtil == null || namaPelatihan.isEmpty() || status.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.sql.Date tglMulai = new java.sql.Date(tglMulaiUtil.getTime());
        java.sql.Date tglSelesai = new java.sql.Date(tglSelesaiUtil.getTime());

        int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin memperbarui pelatihan ini?",
            "Konfirmasi Perbarui",
            JOptionPane.YES_NO_OPTION);

        if(konfirmasi != JOptionPane.YES_OPTION) return;

        try (Connection conn = koneksi.getConnection()) {
            PreparedStatement cekNama = conn.prepareStatement(
            "SELECT nama_pelatihan FROM pelatihan WHERE LOWER(nama_pelatihan) = LOWER(?) AND id_pelatihan <> ?");
            cekNama.setString(1, namaPelatihan);
            cekNama.setString(2, idPelatihan); 
            ResultSet rsNama = cekNama.executeQuery();

            if (rsNama.next()) {
                JOptionPane.showMessageDialog(this,
                    "Nama Pelatihan sudah terdaftar untuk ID lain!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            String sql = "UPDATE pelatihan SET tanggal_mulai=?, tanggal_selesai=?, nama_pelatihan=?, deskripsi=?, status_program=? WHERE id_pelatihan=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setDate(1, tglMulai);
            pst.setDate(2, tglSelesai);
            pst.setString(3, namaPelatihan);
            pst.setString(4, deskripsi);
            pst.setString(5, status);
            pst.setString(6, idPelatihan);

            if(pst.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Pelatihan berhasil diperbarui!");
                loadDataPelatihan();
            } else {
                JOptionPane.showMessageDialog(this, "ID Pelatihan tidak ditemukan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui pelatihan: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        adminStaff adminstaff = new adminStaff();
        adminstaff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        adminPelatihan adminpelatihan = null;
        try {
            adminpelatihan = new adminPelatihan();
        } catch (Exception ex) {
            System.getLogger(adminPelatihan.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        adminpelatihan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        adminPeserta adminpeserta = new adminPeserta();
        adminpeserta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        adminPendaftar adminpendaftar = new adminPendaftar();
        adminpendaftar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String idPelatihan = jTextField2.getText().trim();
        String namaPelatihan = jTextField4.getText().trim();
        String deskripsi = jTextField6.getText().trim();
        String status = jComboBox1.getSelectedItem().toString();

        java.util.Date tglMulaiUtil = jDateChooser1.getDate();
        java.util.Date tglSelesaiUtil = jDateChooser2.getDate();

        if(idPelatihan.isEmpty() || tglMulaiUtil == null || tglSelesaiUtil == null || 
           namaPelatihan.isEmpty() || status.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi kecuali deskripsi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(!idPelatihan.startsWith("PL")) {
            JOptionPane.showMessageDialog(this, "ID Pelatihan harus diawali 'PL'!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.sql.Date tglMulai = new java.sql.Date(tglMulaiUtil.getTime());
        java.sql.Date tglSelesai = new java.sql.Date(tglSelesaiUtil.getTime());

        int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menambahkan pelatihan ini?", 
            "Konfirmasi Tambah", 
            JOptionPane.YES_NO_OPTION);

        if(konfirmasi != JOptionPane.YES_OPTION) return;

        try (Connection conn = koneksi.getConnection()) {

            PreparedStatement cek = conn.prepareStatement("SELECT id_pelatihan FROM pelatihan WHERE id_pelatihan=?");
            cek.setString(1, idPelatihan);
            ResultSet rs = cek.executeQuery();
            if(rs.next()) {
                JOptionPane.showMessageDialog(this, "ID Pelatihan sudah ada!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            PreparedStatement pst = conn.prepareStatement(
                "INSERT INTO pelatihan(id_pelatihan, tanggal_mulai, tanggal_selesai, nama_pelatihan, deskripsi, status_program) VALUES(?,?,?,?,?,?)");

            pst.setString(1, idPelatihan);
            pst.setDate(2, tglMulai);
            pst.setDate(3, tglSelesai);
            pst.setString(4, namaPelatihan);
            pst.setString(5, deskripsi);
            pst.setString(6, status);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Pelatihan berhasil ditambahkan!");
            loadDataPelatihan();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan pelatihan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new adminPelatihan().setVisible(true);
            } catch (Exception ex) {
                System.getLogger(adminPelatihan.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
