/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Model.peserta;
import Service.pesertaService;
import java.sql.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import util.koneksi;
/**
 *
 * @author user
 */
public class adminPeserta extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminPeserta.class.getName());
        private void loadDataPeserta() {
            pesertaService service = new pesertaService();
            List<peserta> daftarPeserta = service.getAllPeserta();

            DefaultTableModel model = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            // 🔹 Kolom sesuai tabel yang ditampilkan
            model.addColumn("NIK");
            model.addColumn("Nama");
            model.addColumn("Alamat");
            model.addColumn("Pekerjaan");
            model.addColumn("Penghasilan");
            model.addColumn("Email");
            model.addColumn("No HP");
            model.addColumn("Password");
            model.addColumn("Progress");

            try (Connection conn = koneksi.getConnection()) {
                for (peserta p : daftarPeserta) {
                    String sql = "SELECT * FROM pendaftar WHERE nik = ?";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, p.getNik());
                    ResultSet rs = pst.executeQuery();

                    if (rs.next()) {
                        if (!"Diterima".equalsIgnoreCase(rs.getString("status_verifikasi"))) continue;

                        model.addRow(new Object[]{
                            rs.getString("nik"),
                            rs.getString("nama"),
                            rs.getString("alamat"),
                            rs.getString("pekerjaan"),
                            rs.getString("penghasilan"),
                            rs.getString("email"),
                            rs.getString("no_hp"),
                            rs.getString("password"),
                            p.getProgress() 
                        });
                    }
                }

                jTable2.setModel(model);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error load peserta: " + e.getMessage());
            }
        }

    /**
     * Creates new form adminPeserta
     */
    public adminPeserta() {
        initComponents();
        setLocationRelativeTo(null);
        loadDataPeserta();
        
         jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getClickCount() == 2) {
                int row = jTable2.getSelectedRow();
                if (row != -1) {
                jTextField2.setText(jTable2.getValueAt(row, 0).toString()); 
                jTextField4.setText(jTable2.getValueAt(row, 1).toString()); 
                jTextField6.setText(jTable2.getValueAt(row, 2).toString()); 
                jTextField1.setText(jTable2.getValueAt(row, 3).toString()); 
                jTextField3.setText(jTable2.getValueAt(row, 4).toString()); 
                jTextField5.setText(jTable2.getValueAt(row, 5).toString()); 
                jTextField7.setText(jTable2.getValueAt(row, 6).toString());
                jTextField8.setText(jTable2.getValueAt(row, 7).toString()); 
                jTextField9.setText(jTable2.getValueAt(row, 8).toString()); 
            }
        }
    }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(410, 30));

        jTextField5.setBackground(new java.awt.Color(217, 217, 217));
        jTextField5.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(37, 37, 37));
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(217, 217, 217));
        jTextField6.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(37, 37, 37));
        jTextField6.setBorder(null);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField9.setBackground(new java.awt.Color(217, 217, 217));
        jTextField9.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(37, 37, 37));
        jTextField9.setBorder(null);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addGap(0, 319, Short.MAX_VALUE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 440, 25));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(410, 30));

        jTextField3.setBackground(new java.awt.Color(217, 217, 217));
        jTextField3.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(37, 37, 37));
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(217, 217, 217));
        jTextField4.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(37, 37, 37));
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField8.setBackground(new java.awt.Color(217, 217, 217));
        jTextField8.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(37, 37, 37));
        jTextField8.setBorder(null);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addGap(0, 321, Short.MAX_VALUE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 440, 25));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(410, 30));

        jTextField1.setBackground(new java.awt.Color(217, 217, 217));
        jTextField1.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(37, 37, 37));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(217, 217, 217));
        jTextField2.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(37, 37, 37));
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField7.setBackground(new java.awt.Color(217, 217, 217));
        jTextField7.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(37, 37, 37));
        jTextField7.setBorder(null);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
            .addComponent(jTextField7)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 440, 25));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 52, 188));
        jButton1.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Hapus");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 52, 188));
        jButton2.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Perbarui");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 52, 188));
        jButton4.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Tambah");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 110, 150));

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setFont(new java.awt.Font("Inter 24pt", 0, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(37, 37, 37));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 520, 190));

        jPanel2.setBackground(new java.awt.Color(0, 52, 188));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Inter 24pt", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(37, 37, 37));
        jButton3.setText("Daftar Staff");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Inter 24pt", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(37, 37, 37));
        jButton7.setText("Daftar Pelatihan");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Inter 24pt", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(37, 37, 37));
        jButton8.setText("Daftar Peserta");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Inter 24pt", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(37, 37, 37));
        jButton9.setText("Daftar Pendaftar");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Inter 24pt", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 52, 188));
        jButton5.setText("Keluar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 40, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 40, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 332, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ImageIcon/admin peserta.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nik = jTextField2.getText().trim();

        if(nik.isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIK pendaftar harus diisi untuk menghapus!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus pendaftar dengan NIK: " + nik + "?",
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if(confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try (Connection conn = koneksi.getConnection()) {

            String sqlPeserta = "DELETE FROM peserta WHERE nik=?";
            PreparedStatement pstPeserta = conn.prepareStatement(sqlPeserta);
            pstPeserta.setString(1, nik);
            pstPeserta.executeUpdate();
            pstPeserta.close();

            String sqlPendaftar = "DELETE FROM pendaftar WHERE nik=?";
            PreparedStatement pstPendaftar = conn.prepareStatement(sqlPendaftar);
            pstPendaftar.setString(1, nik);
            int rows = pstPendaftar.executeUpdate();
            pstPendaftar.close();

            if(rows > 0) {
                JOptionPane.showMessageDialog(this, "Pendaftar dan data peserta berhasil dihapus ✅");
                loadDataPeserta();

                jTextField2.setText("");
                jTextField4.setText("");
                jTextField6.setText("");
                jTextField1.setText("");
                jTextField3.setText("");
                jTextField5.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "NIK tidak ditemukan!");
            }

        } catch(SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal hapus pendaftar: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    String nik = jTextField2.getText().trim();
    String nama = jTextField4.getText().trim();
    String alamat = jTextField6.getText().trim();
    String pekerjaan = jTextField1.getText().trim();
    String penghasilan = jTextField3.getText().trim();
    String email = jTextField5.getText().trim();
    String noHp = jTextField7.getText().trim();
    String password = jTextField8.getText().trim();
    String progress = jTextField9.getText().trim();

    String[] values = {nik, nama, alamat, pekerjaan, penghasilan, email, noHp, password, progress};
    String[] fieldNames = {"NIK", "Nama", "Alamat", "Pekerjaan", "Penghasilan", "Email", "No HP", "Password", "Progress"};

    for (int i = 0; i < values.length; i++) {
        if (values[i].isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom " + fieldNames[i] + " wajib diisi!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }

    if (!nama.matches("[a-zA-Z\\s]{5,}")) {
        JOptionPane.showMessageDialog(this, "Nama minimal 5 huruf dan hanya boleh huruf!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
        JOptionPane.showMessageDialog(this, "Format email tidak valid!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (!noHp.matches("\\d{11,}")) {
        JOptionPane.showMessageDialog(this, "No HP minimal 11 digit dan hanya angka!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (!password.matches("^(?=.*[A-Za-z])(?=.*\\d).{6,}$")) {
        JOptionPane.showMessageDialog(this, "Password minimal 6 karakter dan harus ada huruf serta angka!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (!penghasilan.matches("\\d+(\\.\\d{1,2})?")) {
        JOptionPane.showMessageDialog(this, "Penghasilan harus berupa angka!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try (Connection conn = koneksi.getConnection()) {
        conn.setAutoCommit(false); 

        String sqlPendaftar = "UPDATE pendaftar SET nama=?, alamat=?, pekerjaan=?, penghasilan=?, email=?, no_hp=?, password=? WHERE nik=?";
        PreparedStatement pst1 = conn.prepareStatement(sqlPendaftar);
        pst1.setString(1, nama);
        pst1.setString(2, alamat);
        pst1.setString(3, pekerjaan);
        pst1.setString(4, penghasilan);
        pst1.setString(5, email);
        pst1.setString(6, noHp);
        pst1.setString(7, password);
        pst1.setString(8, nik);
        int updatedPendaftar = pst1.executeUpdate();
        pst1.close();


        String sqlPeserta = "UPDATE peserta SET progress=? WHERE nik=?";
        PreparedStatement pst2 = conn.prepareStatement(sqlPeserta);
        pst2.setString(1, progress);
        pst2.setString(2, nik);
        int updatedPeserta = pst2.executeUpdate();
        pst2.close();

        if (updatedPendaftar > 0 || updatedPeserta > 0) {
            conn.commit(); 
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            loadDataPeserta(); 
        } else {
            conn.rollback();
            JOptionPane.showMessageDialog(this, "NIK tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

      
        if ("100%".equals(progress)) {
            try (Connection conn2 = koneksi.getConnection()) {
                PreparedStatement ps = conn2.prepareStatement(
                    "SELECT id_peserta FROM peserta WHERE nik = ?"
                );
                ps.setString(1, nik);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    String idPeserta = rs.getString("id_peserta");
                    PreparedStatement cekSertifikat = conn2.prepareStatement(
                        "SELECT * FROM sertifikat WHERE id_peserta = ?"
                    );
                    cekSertifikat.setString(1, idPeserta);
                    ResultSet rsCek = cekSertifikat.executeQuery();

                    if (!rsCek.next()) {
                        String lastNumber = "SRT000";
                        Statement stmt = conn2.createStatement();
                        ResultSet rsLast = stmt.executeQuery(
                            "SELECT nomor_sertifikat FROM sertifikat ORDER BY nomor_sertifikat DESC LIMIT 1"
                        );
                        if (rsLast.next()) {
                            lastNumber = rsLast.getString("nomor_sertifikat");
                        }

                        int newNumber = Integer.parseInt(lastNumber.replace("SRT", "")) + 1;
                        String newNomor = String.format("SRT%03d", newNumber);

                        PreparedStatement insert = conn2.prepareStatement(
                            "INSERT INTO sertifikat (nomor_sertifikat, skor_pelatihan, tanggal_terbit, id_peserta) VALUES (?, ?, ?, ?)"
                        );
                        insert.setString(1, newNomor);
                        insert.setInt(2, 0);
                        insert.setDate(3, new java.sql.Date(System.currentTimeMillis()));
                        insert.setString(4, idPeserta);
                        insert.executeUpdate();

                        JOptionPane.showMessageDialog(this,
                            "Progress 100%! Sertifikat otomatis dibuat.\nNomor: " + newNomor,
                            "Sertifikat Dibuat", JOptionPane.INFORMATION_MESSAGE);
                    }
                    rsCek.close();
                    cekSertifikat.close();
                }
                rs.close();
                ps.close();

            } catch (SQLException ex2) {
                JOptionPane.showMessageDialog(this,
                    "Gagal membuat sertifikat otomatis: " + ex2.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
                ex2.printStackTrace();
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:                                        
    String nik = jTextField2.getText().trim();
    String nama = jTextField4.getText().trim();
    String alamat = jTextField6.getText().trim();
    String pekerjaan = jTextField1.getText().trim();
    String penghasilan = jTextField3.getText().trim();
    String email = jTextField5.getText().trim();
    String noHp = jTextField7.getText().trim();
    String password = jTextField8.getText().trim();

    String[] values = {nik, nama, alamat, pekerjaan, penghasilan, email, noHp, password};
    String[] fieldNames = {"NIK", "Nama", "Alamat", "Pekerjaan", "Penghasilan", "Email", "No HP", "Password"};

    for (int i = 0; i < values.length; i++) {
        if (values[i].isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom " + fieldNames[i] + " wajib diisi!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }
    
    if (!nama.matches("[a-zA-Z\\s]{5,}")) {
        JOptionPane.showMessageDialog(this, "Nama minimal 5 huruf dan hanya boleh huruf!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (nik.length() < 16 || !nik.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "NIK minimal 16 digit dan hanya angka!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
        JOptionPane.showMessageDialog(this, "Format email tidak valid!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (!noHp.matches("\\d{11,}")) {
        JOptionPane.showMessageDialog(this, "No HP minimal 11 digit dan hanya angka!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (!password.matches("^(?=.*[A-Za-z])(?=.*\\d).{6,}$")) {
        JOptionPane.showMessageDialog(this, "Password minimal 6 karakter dan harus ada huruf serta angka!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (!penghasilan.matches("\\d+(\\.\\d{1,2})?")) {
        JOptionPane.showMessageDialog(this, "Penghasilan harus berupa angka!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try (Connection conn = koneksi.getConnection()) {
        PreparedStatement cek = conn.prepareStatement("SELECT * FROM pendaftar WHERE nik = ?");
        cek.setString(1, nik);
        ResultSet rcek = cek.executeQuery();

        if (rcek.next()) {
            JOptionPane.showMessageDialog(this, "Pendaftar dengan NIK ini sudah ada!", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        rcek.close();
        cek.close();

        String sql = "INSERT INTO pendaftar (nik, nama, alamat, pekerjaan, penghasilan, email, no_hp, password, status_verifikasi) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, nik);
        pst.setString(2, nama);
        pst.setString(3, alamat);
        pst.setString(4, pekerjaan);
        pst.setString(5, penghasilan);
        pst.setString(6, email);
        pst.setString(7, noHp);
        pst.setString(8, password);
        pst.setString(9, "Menunggu"); 

        pst.executeUpdate();
        pst.close();

        JOptionPane.showMessageDialog(this, "Pendaftar berhasil ditambahkan ✅", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        loadDataPeserta(); 

        jTextField2.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        jTextField1.setText("");
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField7.setText("");
        jTextField8.setText("");

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        adminStaff adminstaff = new adminStaff();
        adminstaff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        adminPelatihan adminpelatihan = null;
        try {
            adminpelatihan = new adminPelatihan();
        } catch (Exception ex) {
            System.getLogger(adminPelatihan.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        adminpelatihan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        adminPeserta adminpeserta = new adminPeserta();
        adminpeserta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        adminPendaftar adminpendaftar = new adminPendaftar();
        adminpendaftar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminPeserta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
