/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.sql.Connection;
import javax.swing.JOptionPane;
import util.koneksi;

/**
 *
 * @author user
 */
public class Daftar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Daftar.class.getName());

    /**
     * Creates new form Daftar
     */
    public Daftar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        alamat = new javax.swing.JTextField();
        NIK = new javax.swing.JTextField();
        naleng = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        pekerjaan = new javax.swing.JTextField();
        penghasilan = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alamat.setBackground(new java.awt.Color(213, 213, 213));
        alamat.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        alamat.setForeground(new java.awt.Color(37, 37, 37));
        alamat.setBorder(null);
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 160, 30));

        NIK.setBackground(new java.awt.Color(213, 213, 213));
        NIK.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        NIK.setForeground(new java.awt.Color(37, 37, 37));
        NIK.setBorder(null);
        jPanel1.add(NIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 160, 30));

        naleng.setBackground(new java.awt.Color(213, 213, 213));
        naleng.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        naleng.setForeground(new java.awt.Color(37, 37, 37));
        naleng.setBorder(null);
        jPanel1.add(naleng, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 330, 30));

        email.setBackground(new java.awt.Color(213, 213, 213));
        email.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(37, 37, 37));
        email.setBorder(null);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 160, 30));

        nohp.setBackground(new java.awt.Color(213, 213, 213));
        nohp.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        nohp.setForeground(new java.awt.Color(37, 37, 37));
        nohp.setBorder(null);
        nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nohpActionPerformed(evt);
            }
        });
        jPanel1.add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 160, 30));

        pekerjaan.setBackground(new java.awt.Color(213, 213, 213));
        pekerjaan.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        pekerjaan.setForeground(new java.awt.Color(37, 37, 37));
        pekerjaan.setBorder(null);
        jPanel1.add(pekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 160, 30));

        penghasilan.setBackground(new java.awt.Color(213, 213, 213));
        penghasilan.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        penghasilan.setForeground(new java.awt.Color(37, 37, 37));
        penghasilan.setBorder(null);
        penghasilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penghasilanActionPerformed(evt);
            }
        });
        jPanel1.add(penghasilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 160, 30));

        password.setBackground(new java.awt.Color(213, 213, 213));
        password.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        password.setForeground(new java.awt.Color(37, 37, 37));
        password.setBorder(null);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 330, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Inter 24pt", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 52, 188));
        jButton1.setText("Masuk");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 90, 40));

        jButton2.setBackground(new java.awt.Color(0, 52, 188));
        jButton2.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Daftar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 80, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 52, 188));
        jButton3.setText("Kembali");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 82, 60, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ImageIcon/daftar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void penghasilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penghasilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penghasilanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String[] values = {
            NIK.getText(),
            naleng.getText(),
            alamat.getText(),
            pekerjaan.getText(),
            penghasilan.getText(),
            email.getText(),
            nohp.getText(),
            new String(password.getPassword())
        };

        String[] fieldNames = {
            "NIK",
            "Nama Lengkap",
            "Alamat",
            "Pekerjaan",
            "Penghasilan",
            "Email",
            "No HP",
            "Password"
        };

        for (int i = 0; i < values.length; i++) {
            if (values[i].isEmpty()) {
                JOptionPane.showMessageDialog(this, "Kolom " + fieldNames[i] + " wajib diisi!");
                return;
            }
        }
        
        if (values[0].length() != 16 || !values[0].matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "NIK harus terdiri dari 16 digit angka!");
            return;
        }
        
        if (values[1].length() < 5) {
            JOptionPane.showMessageDialog(this, "Nama Lengkap minimal harus 5 karakter!");
            return;
        }
        
        if (!values[4].matches("\\d+(\\.\\d{1,2})?")) {
            JOptionPane.showMessageDialog(this, "Penghasilan harus berupa angka!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!values[5].matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            JOptionPane.showMessageDialog(this, "Format email tidak valid!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (values[6].length() < 11 || !values[6].matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Kolom No HP minimal harus 11 digit dan hanya angka!");
            return;
        }

        if (values[7].length() < 6 || !values[7].matches("^(?=.*[A-Za-z])(?=.*\\d).+$")) {
            JOptionPane.showMessageDialog(this, "Password minimal 6 karakter, harus mengandung huruf dan angka!");
            return;
        }
        

        try (Connection conn = koneksi.getConnection()) {
            String cekSql = "SELECT * FROM pendaftar WHERE nik = ?";
            try (var ps = conn.prepareStatement(cekSql)) {
                ps.setString(1, values[0]); // NIK
                var rs = ps.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "NIK sudah terdaftar!");
                    return;
                }
            }

            String sql = "INSERT INTO pendaftar (nik, nama, alamat, pekerjaan, penghasilan, email, no_hp, password) VALUES (?,?,?,?,?,?,?,?)";
            try (var ps = conn.prepareStatement(sql)) {
                for (int i = 0; i < values.length; i++) {
                    ps.setString(i + 1, values[i]);
                }
                ps.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Pendaftaran berhasil!");

            NIK.setText("");
            naleng.setText("");
            alamat.setText("");
            pekerjaan.setText("");
            penghasilan.setText("");
            email.setText("");
            nohp.setText("");
            password.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal daftar: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nohpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Daftar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIK;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField naleng;
    private javax.swing.JTextField nohp;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField pekerjaan;
    private javax.swing.JTextField penghasilan;
    // End of variables declaration//GEN-END:variables
}
