/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import util.koneksi;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NIK1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        MasukBtn = new javax.swing.JButton();
        BelumadaAkun = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NIK1.setBackground(new java.awt.Color(213, 213, 213));
        NIK1.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        NIK1.setForeground(new java.awt.Color(37, 37, 37));
        NIK1.setAlignmentX(3.0F);
        NIK1.setAlignmentY(3.0F);
        NIK1.setBorder(null);
        NIK1.setMargin(new java.awt.Insets(10, 6, 10, 6));
        NIK1.setPreferredSize(new java.awt.Dimension(116, 30));
        NIK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIK1ActionPerformed(evt);
            }
        });
        jPanel1.add(NIK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 230, 30));

        jPasswordField1.setBackground(new java.awt.Color(213, 213, 213));
        jPasswordField1.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(37, 37, 37));
        jPasswordField1.setBorder(null);
        jPasswordField1.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 230, 30));

        MasukBtn.setBackground(new java.awt.Color(0, 52, 188));
        MasukBtn.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        MasukBtn.setForeground(new java.awt.Color(255, 255, 255));
        MasukBtn.setText("Masuk");
        MasukBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukBtnActionPerformed(evt);
            }
        });
        jPanel1.add(MasukBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, 30));

        BelumadaAkun.setFont(new java.awt.Font("Inter 24pt", 0, 10)); // NOI18N
        BelumadaAkun.setForeground(new java.awt.Color(37, 37, 37));
        BelumadaAkun.setText("Belum punya akun?");
        jPanel1.add(BelumadaAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 100, 10));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Inter 24pt", 0, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(37, 37, 37));
        jButton1.setText("Daftar Sekarang");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ImageIcon/LOGINJAVA.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -4, 800, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MasukBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukBtnActionPerformed
            String nik = NIK1.getText(); 
      String password = new String(jPasswordField1.getPassword());

    if(nik.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "NIK dan Password tidak boleh kosong!", "Login Gagal", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        Connection conn = koneksi.getConnection();

        String sqlPeserta = "SELECT status_verifikasi FROM pendaftar WHERE nik=? AND password=?";
        PreparedStatement pstPeserta = conn.prepareStatement(sqlPeserta);
        pstPeserta.setString(1, nik);
        pstPeserta.setString(2, password);
        ResultSet rsPeserta = pstPeserta.executeQuery();

        if(rsPeserta.next()) {
            String statusVerifikasi = rsPeserta.getString("status_verifikasi");

            switch(statusVerifikasi.toLowerCase()) {
                case "diterima" -> {
                    utamaPeserta formPeserta = new utamaPeserta(nik); 
                    formPeserta.setVisible(true);
                    this.dispose();
                    setLocationRelativeTo(null);
                }
                case "menunggu" -> JOptionPane.showMessageDialog(this, 
                        "Akun anda masih dalam tahap verifikasi oleh admin, coba lagi nanti",
                        "Verifikasi", JOptionPane.INFORMATION_MESSAGE);
                case "ditolak" -> JOptionPane.showMessageDialog(this, 
                        "Maaf akun anda tidak lolos tahap verifikasi, hubungi call center jika membutuhkan info lebih lanjut",
                        "Verifikasi", JOptionPane.ERROR_MESSAGE);
            }

        } else {
        String sqlStaff = "SELECT id_staff, nama, email, no_hp, password, jenis_staff FROM staff WHERE id_staff=? AND password=?";
            try (PreparedStatement pstStaff = conn.prepareStatement(sqlStaff)) {
                pstStaff.setString(1, nik);
                pstStaff.setString(2, password);
            try (ResultSet rsStaff = pstStaff.executeQuery()) {
                if(rsStaff.next()) {
                    String idStaff = rsStaff.getString("id_staff");
                    String nama = rsStaff.getString("nama");
                    String email = rsStaff.getString("email");
                    String nohp = rsStaff.getString("no_hp");
                    String pass = rsStaff.getString("password");
                    String jenis = rsStaff.getString("jenis_staff").trim();
                    
                    Model.roleStaff role;

                    if (jenis.equalsIgnoreCase("Admin")) {
                        role = new Model.admin(idStaff, nama, email, nohp, pass);
                        role.tugasUtama();
                        new adminPelatihan().setVisible(true);

                    } else if (jenis.equalsIgnoreCase("Staff Pelatihan")) {
                        role = new Model.staffPelatihan(idStaff, nama, email, nohp, pass);
                        role.tugasUtama();
                        new utamaStaff().setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(this, "Jenis staff tidak dikenali! (" + jenis + ")", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                    
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "NIK / ID Staff atau Password salah!", "Login Gagal", JOptionPane.ERROR_MESSAGE);
                }
            }
            }
        }

        rsPeserta.close();
        pstPeserta.close();
        conn.close();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_MasukBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Daftar daftar = new Daftar();
        daftar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NIK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIK1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIK1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BelumadaAkun;
    private javax.swing.JButton MasukBtn;
    private javax.swing.JTextField NIK1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
