/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import util.koneksi;

/**
 *
 * @author user
 */
public class perbaruiAkun extends javax.swing.JFrame {
    private String nikPeserta;
    
        public perbaruiAkun(String nikPeserta) throws Exception {
        this.nikPeserta = nikPeserta;
        initComponents();
        setLocationRelativeTo(null);
        loadDataPesertaLogin(); 
    }

    private void loadDataPesertaLogin() throws Exception {
        String sql = "SELECT pd.nama, pd.alamat, pd.pekerjaan, pd.penghasilan, " +
             "pd.email, pd.no_hp, pd.password " +
             "FROM pendaftar pd JOIN peserta p ON pd.nik = p.nik " +
             "WHERE pd.nik = ?";

        try (Connection conn = koneksi.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setString(1, nikPeserta);
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    naleng.setText(rs.getString("nama"));
                    alamat.setText(rs.getString("alamat"));
                    pekerjaan.setText(rs.getString("pekerjaan"));
                    penghasilan.setText(rs.getString("penghasilan"));
                    email.setText(rs.getString("email"));
                    nohp.setText(rs.getString("no_hp"));
                    password.setText(rs.getString("password"));
                    NIK.setText(nikPeserta);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data peserta: " + e.getMessage());
        }
    }
    /**
     * Creates new form perbaruiAkun
     */
    public perbaruiAkun() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        pekerjaan = new javax.swing.JTextField();
        naleng = new javax.swing.JTextField();
        penghasilan = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        NIK = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setBackground(new java.awt.Color(213, 213, 213));
        password.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        password.setForeground(new java.awt.Color(37, 37, 37));
        password.setBorder(null);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 330, 30));

        pekerjaan.setBackground(new java.awt.Color(213, 213, 213));
        pekerjaan.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        pekerjaan.setForeground(new java.awt.Color(37, 37, 37));
        pekerjaan.setBorder(null);
        jPanel1.add(pekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 160, 30));

        naleng.setBackground(new java.awt.Color(213, 213, 213));
        naleng.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        naleng.setForeground(new java.awt.Color(37, 37, 37));
        naleng.setBorder(null);
        jPanel1.add(naleng, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 330, 30));

        penghasilan.setBackground(new java.awt.Color(213, 213, 213));
        penghasilan.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        penghasilan.setForeground(new java.awt.Color(37, 37, 37));
        penghasilan.setBorder(null);
        penghasilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penghasilanActionPerformed(evt);
            }
        });
        jPanel1.add(penghasilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 160, 30));

        alamat.setBackground(new java.awt.Color(213, 213, 213));
        alamat.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        alamat.setForeground(new java.awt.Color(37, 37, 37));
        alamat.setBorder(null);
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 160, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 52, 188));
        jButton3.setText("Kembali");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 82, 60, 30));

        email.setBackground(new java.awt.Color(213, 213, 213));
        email.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(37, 37, 37));
        email.setBorder(null);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 160, 30));

        jButton2.setBackground(new java.awt.Color(0, 52, 188));
        jButton2.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Perbarui");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 80, 30));

        NIK.setBackground(new java.awt.Color(213, 213, 213));
        NIK.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        NIK.setForeground(new java.awt.Color(37, 37, 37));
        NIK.setBorder(null);
        jPanel1.add(NIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 160, 30));

        nohp.setBackground(new java.awt.Color(213, 213, 213));
        nohp.setFont(new java.awt.Font("Inter 24pt", 1, 12)); // NOI18N
        nohp.setForeground(new java.awt.Color(37, 37, 37));
        nohp.setBorder(null);
        jPanel1.add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ImageIcon/perbaruiAkun.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void penghasilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penghasilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penghasilanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nama = naleng.getText().trim();
        String alamatText = alamat.getText().trim();
        String pekerjaanText = pekerjaan.getText().trim();
        String penghasilanText = penghasilan.getText().trim();
        String emailText = email.getText().trim();
        String noHp = nohp.getText().trim();
        String passwordText = password.getText().trim();
        String nik = nikPeserta; // dari konstruktor

        // --- VALIDASI ---
        String[] values = { nama, alamatText, pekerjaanText, penghasilanText, emailText, noHp, passwordText };
        String[] fieldNames = { "Nama", "Alamat", "Pekerjaan", "Penghasilan", "Email", "No HP", "Password" };

        for (int i = 0; i < values.length; i++) {
            if (values[i].isEmpty()) {
                JOptionPane.showMessageDialog(this, "Kolom " + fieldNames[i] + " wajib diisi!",
                        "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        if (!nama.matches("[a-zA-Z\\s]{5,}")) {
            JOptionPane.showMessageDialog(this, "Nama minimal 5 huruf dan hanya boleh huruf!",
                    "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (nik.length() != 16 || !nik.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "NIK harus terdiri dari tepat 16 digit angka!",
                    "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!emailText.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            JOptionPane.showMessageDialog(this, "Format email tidak valid!",
                    "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!noHp.matches("\\d{11,}")) {
            JOptionPane.showMessageDialog(this, "No HP minimal 11 digit dan hanya angka!",
                    "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!passwordText.matches("^(?=.*[A-Za-z])(?=.*\\d).{6,}$")) {
            JOptionPane.showMessageDialog(this, "Password minimal 6 karakter dan harus ada huruf serta angka!",
                    "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!penghasilanText.matches("\\d+(\\.\\d{1,2})?")) {
            JOptionPane.showMessageDialog(this, "Penghasilan harus berupa angka!",
                    "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- Jika semua validasi lolos, baru lanjut UPDATE ---
        String sqlUpdate = "UPDATE pendaftar pd JOIN peserta p ON pd.nik=p.nik " +
                           "SET pd.nama=?, pd.alamat=?, pd.pekerjaan=?, pd.penghasilan=?, " +
                           "pd.email=?, pd.no_hp=?, pd.password=? WHERE p.nik=?";

        try (Connection conn = koneksi.getConnection();
             PreparedStatement pst = conn.prepareStatement(sqlUpdate)) {

            pst.setString(1, nama);
            pst.setString(2, alamatText);
            pst.setString(3, pekerjaanText);
            pst.setString(4, penghasilanText);
            pst.setString(5, emailText);
            pst.setString(6, noHp);
            pst.setString(7, passwordText);
            pst.setString(8, nik);

            int updated = pst.executeUpdate();
            if (updated > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            } else {
                JOptionPane.showMessageDialog(this, "Tidak ada data yang diperbarui.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data: " + e.getMessage());
        } catch (Exception ex) {
            System.getLogger(perbaruiAkun.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            utamaPeserta home = new utamaPeserta(nikPeserta); 
            home.setVisible(true);
            this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> new perbaruiAkun().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIK;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField naleng;
    private javax.swing.JTextField nohp;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField pekerjaan;
    private javax.swing.JTextField penghasilan;
    // End of variables declaration//GEN-END:variables
}
